- name: node-exporter
  hosts: all
  become: yes
  roles:
    - role: install-node-exporter-tls
      tags: [ install-node-exporter-tls ]
      vars:
        - monitoring_ip: "{{ monitoring_ip }}"

    - role: install-node-exporter-non-tls
      tags: [ install-node-exporter-non-tls ]
      vars:
        - basic_auth_user: " {{ basic_auth_user }} "
        - basic_auth_pass: " {{ basic_auth_pass }} "

    - role: delete-node-exporter
      tags: [ delete-node-exporter ]
      vars:
        - monitoring_ip: "{{  }}"

